name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.1, v1.1.0, etc.

jobs:
  build-and-release:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install py2app
        
    - name: Install create-dmg
      run: |
        brew install create-dmg
        
    - name: Build macOS app
      run: |
        # Clean previous builds
        rm -rf build/ dist/
        
        # Build the app
        python setup.py py2app
        
    - name: Create DMG
      run: |
        # Get version from tag
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "Building version: $VERSION"
        
        # Create DMG
        APP_NAME="Beautiful Flower Display"
        DMG_NAME="Beautiful-Flower-Display-${VERSION}.dmg"
        
        create-dmg \
          --volname "${APP_NAME}" \
          --window-pos 200 120 \
          --window-size 600 300 \
          --icon-size 100 \
          --icon "${APP_NAME}.app" 175 120 \
          --hide-extension "${APP_NAME}.app" \
          --app-drop-link 425 120 \
          "${DMG_NAME}" \
          "dist/"
          
        echo "DMG created: ${DMG_NAME}"
        
    - name: Upload DMG to release
      uses: actions/upload-artifact@v3
      with:
        name: Beautiful-Flower-Display-${{ github.ref_name }}
        path: Beautiful-Flower-Display-*.dmg
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: Beautiful-Flower-Display-*.dmg
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
